name: Main CI

on:
  push:

concurrency:
  group: main-ci
  cancel-in-progress: false

jobs:
  assets:
    name: Assets Package
    uses: ./.github/workflows/assets.yaml
    secrets: inherit

  api:
    name: API Package
    uses: ./.github/workflows/api.yaml
    secrets: inherit

  core:
    name: Core Package
    uses: ./.github/workflows/core.yaml
    secrets: inherit
    needs: [assets, api]

  js:
    name: Platforms / JS
    uses: ./.github/workflows/js.yaml
    secrets: inherit
    needs: [api, core]

  react:
    name: Platforms / React
    uses: ./.github/workflows/react.yaml
    secrets: inherit
    needs: [api, core]